language: node_js
node_js: stable
branchs:
  only:
  - develop
before_install:
- export TZ='Asia/Shanghai'
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- cd .public
- git init
- git config --global user.name "Tony Deng"
- git config --global user.email "wolf.deng@gmail.com"
- git add .
- git commit -m 'update'
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
env:
  global:
  - GH_REF: github.com/tonydeng/tonydeng.github.io.git
